
name: Backend(DemoSyp) Docker (for LeoCloud)

env:
  ContainerName: demosypapi        # Name of the (docker-)container
  SolutionPath: Backend            # sub-directory of sln file location
  SolutionName: DemoSyp.sln        # Replace with your solution name, i.e. MyWpfApp.sln.
  AppProject: WebApi/WebApi.csproj # Replace with the path to your app project, i.e. MyWpfApp\MyWpfApp.csproj.
  CloudNameSpace: student-h-aitenbichler
  AppPrefix: demosypapi
  
on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          #context: "{{defaultContext}}:Src"
          context: ./Backend
          file: ./Backend/WebApi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.ContainerName}}:latest

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete --ignore-not-found -n ${{ env.CloudNameSpace }} deployment ${{ env.AppPrefix }}

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete --ignore-not-found -n ${{ env.CloudNameSpace }} service ${{ env.AppPrefix }}-svc

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete --ignore-not-found -n ${{ env.CloudNameSpace }} ingress ${{ env.AppPrefix }}-ingress

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete --ignore-not-found -n ${{ env.CloudNameSpace }} pod -l app=${{ env.AppPrefix }}

#      - uses: actions-hub/kubectl@master
#        env:
#          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
#        with:
#          args: create -f leocloud-deploy-backend-VolumnsClaim.yaml

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: create -f ./LeoCloud/backend-leocloud-student-h-aitenbichler-demosysapi.yaml

          
